FROM jenkins/jenkins:lts

USER root

# Installation Docker CLI
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc && \
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Installation Python pour scripts et parsing
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv curl jq && \
    pip3 install --break-system-packages requests && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Verification
RUN docker --version && \
    python3 --version && \
    curl --version

USER jenkins

# Pre-install Jenkins plugins
RUN jenkins-plugin-cli --plugins workflow-aggregator:latest htmlpublisher:latest
